[NumPy](http://www.numpy.org/) provides powerful data structures for Python with multi-dimensional arrays and matrices. The execution speeed is faster than Python's native data structures. Take a look at a [benchmarking result](http://arogozhnikov.github.io/2015/01/06/benchmarks-of-speed-numpy-vs-all.html)

Refer the [documentation](https://docs.scipy.org/doc/numpy/reference/) for all the rich features and math functions.

### Import

`numpy` is usually imported as alias `np`

In [1]:
import numpy as np

## Data types in numpy

### Scalars

Numpy scalars provide signed and unsigned with different sizes. For example - `uint8`, `uint16`, `int8`, `int64` etc. Refer [NumPy Data types](https://www.numpy.org/devdocs/user/basics.types.html) for the complete list

Initializing a scalar value `10` as,

In [2]:
a = np.array(10)

Use `shape` attribute to verify the dimension of the array

In [3]:
a.shape

()

We get `()` as the shape of array `a`. It means **Zero dimension** (or scalar). Basic operations can be performed against NumPy scalars

In [4]:
print(a * 10)

100


In [5]:
b = a + 15
b, b.shape

(25, ())

See the type of `b`

In [6]:
type(b)

numpy.int64

### Vectors

Create a vector `(1, 2, 3, 4)`

In [7]:
v = np.array([1, 2, 3, 4])
print(v.shape)

(4,)


The shape `(4,)` represents a **1-dimensional** array. We can access elements like using basic slicing and indexing operations

In [34]:
print(f'v[2] = {v[2]}')
print(f'v[1:] = {v[1:]}')
print(f'v[1:].dtype = {v[1:].dtype}')
print(f'v[1:].shape = {v[1:].shape}')

v[2] = 3
v[1:] = [2 3 4]
v[1:].dtype = int64
v[1:].shape = (3,)


### Matrices

Create a `3 x 2` matrix

In [9]:
m1 = np.array([[1, 2], [5, 6], [10, 12]])
print(m1)
print(f'm1.shape = {m1.shape}')

[[ 1  2]
 [ 5  6]
 [10 12]]
m1.shape = (3, 2)


Access the elements

In [10]:
print(f'm1[2] = {m1[2]}')
print(f'm1[2][1] = {m1[2][1]}')
print(f'm1[1:] = \n{m1[1:]}')

print(f'm1[:2] = \n{m1[:2]}')

m1[2] = [10 12]
m1[2][1] = 12
m1[1:] = 
[[ 5  6]
 [10 12]]
m1[:2] = 
[[1 2]
 [5 6]]


### Reshaping

Change `3 x 2` into different shapes

In [11]:
m2 = m1.reshape(2, 3)
print(m2)
print(m2.shape)

[[ 1  2  5]
 [ 6 10 12]]
(2, 3)


In [12]:
m3 = m1.reshape(1, 6)
print(m3)
print(m3.shape)

[[ 1  2  5  6 10 12]]
(1, 6)


### Tensors

Tensor can have any number of dimensions. For example - `(3 x 3 x 3)`, `(3 x 3 x 2)`.

* A Scalar is a Zero-dimensional tensor - `()`
* A Vector is a 1-D tensor - `(x, )`
* A matrix is a 2-D tensor - `(m, n)`

In [13]:
t1 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])
print(t1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [14]:
print(t1.shape)

(3, 3, 3)


## Matrix operations


### Element-wise operations

Consider two vectors `v1` and `v2`

In [15]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

### Vector and Scalar

NumPy provides support for operation between a vector and a scalar. For example, add `50` to every element of `v1`. We can do all basic operations.

In [16]:
v1 + 50

array([51, 52, 53, 54])

In [17]:
v1 * 5

array([ 5, 10, 15, 20])

### Vector and Vector

We can add, multiply, subtract, divide etc. between two or more vectors.

In [18]:
v1 + v2

array([ 6,  8, 10, 12])

In [19]:
v1 * v2

array([ 5, 12, 21, 32])

### Matrix and scalar

Just like vectors, element-wise operation can be applied to any tensor

In [20]:
m1 = np.array([[1, 2], [3, 4]])
m1 * 10

array([[10, 20],
       [30, 40]])

In [21]:
m1 / 100

array([[0.01, 0.02],
       [0.03, 0.04]])

### Matrix and matrix

In [22]:
m2 = np.array([[5, 6], [7, 8]])
assert(m1.shape == m2.shape)

In [23]:
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [24]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

### Dot Product

Calculate dot product between `a` and `b`

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])

# [1, 2, 3, 4] . [4, 5, 6, 7]
#   = 1x4 + 2x5 + 3x6 + 4x7
#   = 4 + 10 + 18 + 28
#   = 60
#

np.dot(a, b)

60

### Matrix multiplication

The elemet-wise multplication between 2 matrices is performed using `*` operator or `np.multiply` function. To find matrix product, use `np.matmul` function

In [26]:
x1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x1.shape

(2, 4)

In [27]:
x2 = np.array([[4], [1], [2], [0]])
x2.shape

(4, 1)

In [28]:
x3 = np.matmul(x1, x2)
x3

array([[12],
       [40]])

In [29]:
x3.shape

(2, 1)

### Matrix transpose

Use `T` attribute to transpose a matrix

In [30]:
x1, x1.shape

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), (2, 4))

In [35]:
x1.T, x1.T.shape

(array([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]), (4, 2))

## Useful built-in functions

In [47]:
zeros = np.zeros((3, 3))       # Tensor of zeros with shape=(3x3)
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
ones = np.ones((4, 3))         # Tensor of 1s with shape=(4x3)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
identity = np.eye(3, 3)        # Identity matrix (3x3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
r = np.random.random((2, 3))   # Generate random tensor of shape (2x3)
print(r)

[[0.656482   0.43237143 0.01797927]
 [0.4008677  0.81440901 0.2788686 ]]


### Math functions

In [52]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [53]:
np.add(x, y)                  # Element-wise addition

array([[ 6,  8],
       [10, 12]])

In [54]:
np.multiply(x, y)             # Element-wise multiplication

array([[ 5, 12],
       [21, 32]])

In [55]:
np.sqrt(x)                    # Element-wise square root

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [56]:
np.exp(x)                     # Element-wise exponent

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [58]:
# Sum all elements
# 1 + 2 + 3 + 4
np.sum(x)

10

In [60]:
# Sum by column
# [ 1  2
#   3  4 ]
# =>
# [ 4  6]
np.sum(x, axis=0)

array([4, 6])

In [61]:
# Sum by row
# [ 1  2     => [3
#   3  4 ]       7]
np.sum(x, axis=1)

array([3, 7])